// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package infrastructure

import ()

type Circle struct {
	ID     string
	Name   string
	UserID string
}

type User struct {
	ID        string
	FirstName string
	LastName  string
}
